name: all-environments-tofu-apply

on:
  push:
    paths:
      - "tofu/**"
  schedule:
    - cron: "0 2 * * *"  # Runs every day at 2 AM UTC


permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  deploy-multi-tofu:
    uses: evoteum/estate-reusable-workflows/.github/workflows/all-environments-tofu-apply.yml@main
    secrets: inherit
#    with:
#      fail-fast: false
#      environments: '["development", "test"]'
