###################################################################################
# ⚠️ This file is controlled by OpenTofu in the ${CONTROLLER_REPO_NAME} repository.
#    Manual changes will be overwritten the next time OpenTofu runs.
###################################################################################

name: ${WORKFLOW_NAME}

on:
  push:
    paths:
      - "disabled"

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  call-workflow:
    uses: evoteum/${REUSABLE_WORKFLOWS_REPOSITORY}/.github/workflows/${WORKFLOW_NAME}.yml@main
    